version: '3.8'

services:
  # Servicio de SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=12345
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - mynetwork
    volumes:
      - sqlserverdata:/var/opt/mssql

  # Servicio de la aplicación AseguradosAPI
  webapp:
    image: aseguradosapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=GERARDO\\SQLEXPRESS,1433;Database=EmployeeInsuranceDB;User Id=sa;Password=12345;
    ports:
      - "8080:80"
    networks:
      - mynetwork

# Definir red compartida para la comunicación entre contenedores
networks:
  mynetwork:
    driver: bridge

# Volumen para mantener persistencia en SQL Server
volumes:
  sqlserverdata:
